---
- name: Deploy zookeeper instances
  hosts: fusion-zookeeper
  roles:
    - fusion

- name: Wait for zookeeper service
  pause:
    seconds: 30

- name: Deploy fusion cluster
  hosts: fusion-cluster
  roles:
    - fusion
