---
- name: Create fusion config
  template:
    src: fusion.properties.j2
    dest: "{{ app_root }}/fusion/conf/fusion.properties"
    mode: 0644
  notify: restart fusion

- name: Change zookeeper directory permissions
  file:
    path: "{{ app_root }}/fusion/{{ fusion_version }}"
    state: directory
    owner: "{{ fusion_user }}"
    group: "{{ fusion_user }}"
    recurse: yes

- name: Apply fusion systemd unit file
  template:
    src: fusion.service.j2
    dest: "{{ systemd_root }}/fusion.service"
    mode: 0644
  notify: restart fusion

- name: Start fusion service
  systemd: state=started name=fusion daemon_reload=yes enabled=yes
