---
- name: Add java repo
  apt_repository:
    repo: "{{ apt_java_repo }}"
    state: present
    update_cache: yes

- name: Update GPG key for PPA repo
  command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C2518248EEA14886
  become: yes

- name: Accept Oracle License (select)
  debconf: name={{ apt_java_package }} question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  ignore_errors: "{{ ansible_check_mode }}"

- name: Accept Oracle License (seen)
  debconf: name={{ apt_java_package }} question='shared/accepted-oracle-license-v1-1' value='true' vtype='seen'
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install Java
  apt: name={{ apt_java_package }} state=present update_cache=yes force=yes cache_valid_time={{ apt_cache_valid_time }}
  ignore_errors: "{{ ansible_check_mode }}"

- name: Update Java Security
  lineinfile:
    dest: "/etc/java-8-oracle/security/java.policy"
    regexp: "{{ item | regex_escape() }}"
    line: "        {{ item }}"
    insertbefore: "};"
  with_items: "{{ java_security_policies }}"